"""
tests/test_sprint5_jobs.py — Sprint 5 Unit Tests

Coverage:
  - GcodePipeline: parsing, filtering, URL/file detection
  - Job model: state transitions, progress, serialization
  - JobStore: save/load/recover/delete, atomic writes, path safety
  - JobExecutor: full lifecycle (success, pause/resume, cancel, failure)
  - JobManager: submit, queue, FIFO, recovery
"""

import json
import os
import tempfile
import threading
import time
import unittest
from pathlib import Path
from unittest.mock import MagicMock, patch

from src.jobs.gcode_pipeline import load_from_string, load_from_file, _strip_line, _is_executable
from src.jobs.job_model      import Job
from src.jobs.job_store      import JobStore
from src.jobs.job_executor   import JobExecutor
from src.jobs.job_manager    import JobManager
from src.core.models         import StartJobMessage, JobStateMessage


# ─────────────────────────────────────────────────────────────────────
# G-code pipeline
# ─────────────────────────────────────────────────────────────────────

SAMPLE_GCODE = """\
; Generated by Slicer 1.0
%
G28 ; home all axes
M104 S200 ; set nozzle temp
  
M109 S200
G1 X10 Y10 F3000
; just a comment
M84
"""

class TestGcodePipeline(unittest.TestCase):

    def test_filters_comments_and_blanks(self):
        lines = load_from_string(SAMPLE_GCODE)
        for line in lines:
            self.assertFalse(line.startswith(";"))
            self.assertTrue(line.strip())

    def test_filters_percent_marker(self):
        lines = load_from_string(SAMPLE_GCODE)
        self.assertNotIn("%", lines)

    def test_strips_inline_comments(self):
        lines = load_from_string(SAMPLE_GCODE)
        for line in lines:
            self.assertNotIn(";", line)

    def test_correct_line_count(self):
        lines = load_from_string(SAMPLE_GCODE)
        # G28, M104 S200, M109 S200, G1 X10 Y10 F3000, M84 = 5
        self.assertEqual(len(lines), 5)

    def test_order_preserved(self):
        lines = load_from_string(SAMPLE_GCODE)
        self.assertEqual(lines[0], "G28")
        self.assertEqual(lines[1], "M104 S200")

    def test_load_from_file(self):
        with tempfile.NamedTemporaryFile(mode="w", suffix=".gcode", delete=False) as f:
            f.write(SAMPLE_GCODE)
            path = f.name
        try:
            lines = load_from_file(path)
            self.assertEqual(len(lines), 5)
        finally:
            os.unlink(path)

    def test_file_not_found(self):
        from src.jobs.gcode_pipeline import load_from_file
        with self.assertRaises(FileNotFoundError):
            load_from_file("/nonexistent/path/file.gcode")

    def test_is_executable(self):
        self.assertTrue(_is_executable("G28"))
        self.assertTrue(_is_executable("M104 S200"))
        self.assertTrue(_is_executable("T0"))
        self.assertFalse(_is_executable(""))
        self.assertFalse(_is_executable(";comment"))
        self.assertFalse(_is_executable("%"))

    def test_strip_inline_comment(self):
        self.assertEqual(_strip_line("G28 ; home"), "G28")
        self.assertEqual(_strip_line("  M104 S200  "), "M104 S200")
        self.assertEqual(_strip_line("; full comment"), "")


# ─────────────────────────────────────────────────────────────────────
# Job model
# ─────────────────────────────────────────────────────────────────────

class TestJobModel(unittest.TestCase):

    def _make_job(self, lines=None):
        return Job.create(
            printer_id="p1",
            file_url="http://example.com/test.gcode",
            gcode_lines=lines or ["G28", "M104 S200", "M109 S200"],
        )

    def test_create_sets_defaults(self):
        job = self._make_job()
        self.assertEqual(job.status, "QUEUED")
        self.assertEqual(job.current_line_index, 0)
        self.assertEqual(job.progress, 0.0)
        self.assertEqual(job.total_lines, 3)
        self.assertIsNotNone(job.created_at)

    def test_state_transitions(self):
        job = self._make_job()
        job.mark_loading()
        self.assertEqual(job.status, "LOADING")
        job.mark_printing()
        self.assertEqual(job.status, "PRINTING")
        self.assertIsNotNone(job.started_at)
        job.mark_paused()
        self.assertEqual(job.status, "PAUSED")
        job.mark_printing()    # resume
        self.assertIsNone(job.paused_at)
        job.mark_completed()
        self.assertEqual(job.status, "COMPLETED")
        self.assertAlmostEqual(job.progress, 100.0)

    def test_mark_failed(self):
        job = self._make_job()
        job.mark_failed("serial timeout")
        self.assertEqual(job.status, "FAILED")
        self.assertEqual(job.failure_reason, "serial timeout")
        self.assertIsNotNone(job.finished_at)

    def test_mark_cancelled(self):
        job = self._make_job()
        job.mark_cancelled()
        self.assertEqual(job.status, "CANCELLED")

    def test_progress_calculation(self):
        job = self._make_job(["G28"] * 10)
        job.current_line_index = 5
        job.update_progress()
        self.assertAlmostEqual(job.progress, 50.0)

    def test_next_line(self):
        job = self._make_job(["G28", "M104"])
        self.assertEqual(job.next_line, "G28")
        job.current_line_index = 1
        self.assertEqual(job.next_line, "M104")
        job.current_line_index = 2
        self.assertIsNone(job.next_line)

    def test_json_roundtrip(self):
        job = self._make_job()
        job.mark_printing()
        restored = Job.from_json(job.to_json())
        self.assertEqual(restored.job_id,     job.job_id)
        self.assertEqual(restored.status,     job.status)
        self.assertEqual(restored.gcode_lines, job.gcode_lines)
        self.assertEqual(restored.started_at, job.started_at)

    def test_is_active(self):
        job = self._make_job()
        job.mark_printing()
        self.assertTrue(job.is_active)
        job.mark_completed()
        self.assertFalse(job.is_active)
        self.assertTrue(job.is_terminal)


# ─────────────────────────────────────────────────────────────────────
# JobStore
# ─────────────────────────────────────────────────────────────────────

class TestJobStore(unittest.TestCase):

    def setUp(self):
        self.tmpdir = tempfile.mkdtemp()
        self.store  = JobStore(storage_dir=Path(self.tmpdir))

    def _make_job(self):
        return Job.create("p1", "http://x.com/f.gcode", ["G28", "M105"])

    def test_save_and_load(self):
        job = self._make_job()
        self.store.save(job)
        loaded = self.store.load(job.job_id)
        self.assertIsNotNone(loaded)
        self.assertEqual(loaded.job_id, job.job_id)

    def test_load_nonexistent(self):
        self.assertIsNone(self.store.load("does-not-exist"))

    def test_delete(self):
        job = self._make_job()
        self.store.save(job)
        self.store.delete(job.job_id)
        self.assertIsNone(self.store.load(job.job_id))

    def test_load_all(self):
        jobs = [self._make_job() for _ in range(3)]
        for j in jobs:
            self.store.save(j)
        loaded = self.store.load_all()
        self.assertEqual(len(loaded), 3)

    def test_exists(self):
        job = self._make_job()
        self.assertFalse(self.store.exists(job.job_id))
        self.store.save(job)
        self.assertTrue(self.store.exists(job.job_id))

    def test_path_traversal_safe(self):
        """Ensure malicious job IDs cannot write outside storage dir."""
        job = self._make_job()
        job.job_id = "../../etc/passwd"
        # save should succeed but write to safe path inside tmpdir
        self.store.save(job)
        files = list(Path(self.tmpdir).glob("**/*.json"))
        for f in files:
            self.assertTrue(str(f).startswith(self.tmpdir))

    def test_concurrent_writes_safe(self):
        errors = []
        jobs = [self._make_job() for _ in range(10)]

        def writer(j):
            try:
                for _ in range(5):
                    self.store.save(j)
            except Exception as e:
                errors.append(e)

        threads = [threading.Thread(target=writer, args=(j,)) for j in jobs]
        for t in threads: t.start()
        for t in threads: t.join()
        self.assertEqual(errors, [])


# ─────────────────────────────────────────────────────────────────────
# JobExecutor
# ─────────────────────────────────────────────────────────────────────

def _make_ok_result():
    r = MagicMock()
    r.succeeded   = True
    r.elapsed_ms  = 10.0
    r.status.name = "OK"
    return r

def _make_fail_result():
    r = MagicMock()
    r.succeeded   = False
    r.elapsed_ms  = 5.0
    r.status.name = "TIMEOUT"
    return r


class TestJobExecutor(unittest.TestCase):

    def _make_executor(self, lines, engine_result=None, tmpdir=None):
        job = Job.create("p1", "http://x.com/f.gcode", lines)
        engine = MagicMock()
        engine.send.return_value = engine_result or _make_ok_result()
        store   = JobStore(storage_dir=Path(tmpdir or tempfile.mkdtemp()))
        pub     = MagicMock()
        finished = []
        exec_ = JobExecutor(
            job=job,
            command_engine=engine,
            store=store,
            publish_state=pub,
            printer_id="p1",
            on_finished=finished.append,
        )
        return exec_, job, engine, pub, finished

    def _wait(self, condition_fn, timeout=3.0):
        deadline = time.monotonic() + timeout
        while time.monotonic() < deadline:
            if condition_fn():
                return True
            time.sleep(0.05)
        return False

    def test_successful_execution(self):
        lines = ["G28", "M104 S200", "M109 S200"]
        ex, job, engine, pub, finished = self._make_executor(lines)
        ex.start()
        self.assertTrue(self._wait(lambda: job.status == "COMPLETED"))
        self.assertEqual(engine.send.call_count, len(lines))
        self.assertAlmostEqual(job.progress, 100.0)
        self.assertEqual(len(finished), 1)

    def test_engine_sends_lines_in_order(self):
        lines = ["G28", "M104 S200", "G1 X10"]
        ex, job, engine, _, _ = self._make_executor(lines)
        ex.start()
        self._wait(lambda: job.status == "COMPLETED")
        calls = [c[0][0] for c in engine.send.call_args_list]
        self.assertEqual(calls, lines)

    def test_pause_and_resume(self):
        lines = ["G28"] * 20
        ex, job, engine, _, finished = self._make_executor(lines)
        ex.start()
        time.sleep(0.1)
        ex.pause()
        self.assertTrue(self._wait(lambda: job.status == "PAUSED", timeout=2))
        paused_at = job.current_line_index
        time.sleep(0.2)
        self.assertEqual(job.current_line_index, paused_at)  # not advancing
        ex.resume()
        self.assertTrue(self._wait(lambda: job.status == "COMPLETED", timeout=5))

    def test_cancel_stops_execution(self):
        # Use slow engine to give cancel time to fire
        lines = ["G28"] * 100
        engine = MagicMock()
        def slow_send(cmd):
            time.sleep(0.02)
            return _make_ok_result()
        engine.send.side_effect = slow_send
        store   = JobStore(storage_dir=Path(tempfile.mkdtemp()))
        pub     = MagicMock()
        job     = Job.create("p1", "http://x.com/f.gcode", lines)
        finished = []
        ex = JobExecutor(job=job, command_engine=engine, store=store,
                         publish_state=pub, printer_id="p1",
                         on_finished=finished.append)
        ex.start()
        time.sleep(0.1)
        ex.cancel()
        self.assertTrue(self._wait(lambda: job.status == "CANCELLED", timeout=3))
        self.assertLess(job.current_line_index, len(lines))

    def test_engine_failure_marks_job_failed(self):
        lines = ["G28", "M104 S200"]
        ex, job, engine, _, finished = self._make_executor(lines, engine_result=_make_fail_result())
        ex.start()
        self.assertTrue(self._wait(lambda: job.status == "FAILED", timeout=3))
        self.assertIsNotNone(job.failure_reason)
        self.assertEqual(len(finished), 1)

    def test_publish_called_on_every_line(self):
        lines = ["G28", "M104", "M109"]
        ex, job, engine, pub, _ = self._make_executor(lines)
        ex.start()
        self._wait(lambda: job.status == "COMPLETED")
        # at minimum: PRINTING + 3 line updates + COMPLETED
        self.assertGreaterEqual(pub.call_count, len(lines) + 1)


# ─────────────────────────────────────────────────────────────────────
# JobManager
# ─────────────────────────────────────────────────────────────────────

class TestJobManager(unittest.TestCase):

    def _make_manager(self, tmpdir=None):
        engine = MagicMock()
        engine.send.return_value = _make_ok_result()
        pub     = MagicMock()
        store   = JobStore(storage_dir=Path(tmpdir or tempfile.mkdtemp()))
        mgr     = JobManager(
            command_engine=engine,
            publish_state=pub,
            printer_id="p1",
            store=store,
        )
        return mgr, engine, pub, store

    def _start_msg(self, lines_str=None):
        # Uses a local file with real content
        lines = lines_str or "G28\nM104 S200\nM109 S200\n"
        f = tempfile.NamedTemporaryFile(mode="w", suffix=".gcode", delete=False)
        f.write(lines)
        f.close()
        return StartJobMessage(
            printerId="p1",
            jobId=f"job-{id(f)}",
            fileUrl=f.name,
        ), f.name

    def _wait(self, cond, timeout=4.0):
        deadline = time.monotonic() + timeout
        while time.monotonic() < deadline:
            if cond():
                return True
            time.sleep(0.05)
        return False

    def test_submit_and_complete(self):
        mgr, _, _, _ = self._make_manager()
        msg, path = self._start_msg()
        try:
            job = mgr.submit(msg)
            self.assertTrue(self._wait(lambda: job.status == "COMPLETED"))
        finally:
            os.unlink(path)

    def test_only_one_active_job(self):
        mgr, engine, _, _ = self._make_manager()
        # Slow engine so first job stays active
        def slow_send(cmd):
            time.sleep(0.05)
            return _make_ok_result()
        engine.send.side_effect = slow_send

        msg1, p1 = self._start_msg("G28\nM104\nM109\nG1 X10\nG1 X20\n")
        msg2, p2 = self._start_msg("G28\nM105\n")
        try:
            job1 = mgr.submit(msg1)
            time.sleep(0.05)
            job2 = mgr.submit(msg2)
            # job2 must be QUEUED while job1 is running
            self.assertIn(job2.status, ("QUEUED",))
            self._wait(lambda: job1.status == "COMPLETED", timeout=5)
            self._wait(lambda: job2.status == "COMPLETED", timeout=5)
        finally:
            os.unlink(p1); os.unlink(p2)

    def test_cancel_queued_job(self):
        mgr, engine, _, _ = self._make_manager()
        def slow_send(cmd):
            time.sleep(0.1)
            return _make_ok_result()
        engine.send.side_effect = slow_send

        msg1, p1 = self._start_msg("G28\nM104\nM109\nG1 X10\nG1 X20\n")
        msg2, p2 = self._start_msg("G28\n")
        try:
            mgr.submit(msg1)
            time.sleep(0.05)
            job2 = mgr.submit(msg2)
            ok = mgr.cancel(msg2.jobId)
            self.assertTrue(ok)
            self.assertEqual(job2.status, "CANCELLED")
        finally:
            os.unlink(p1); os.unlink(p2)

    def test_recover_requeues_interrupted_jobs(self):
        tmpdir = tempfile.mkdtemp()
        mgr, engine, _, store = self._make_manager(tmpdir=tmpdir)

        # Manually persist a mid-execution job
        job = Job.create("p1", "/dev/null", ["G28", "M104", "M109"])
        job.status             = "PRINTING"
        job.current_line_index = 1
        job.started_at         = "2026-01-01T00:00:00+00:00"
        store.save(job)

        # New manager on same store simulates restart
        mgr2, _, _, _ = self._make_manager(tmpdir=tmpdir)
        # Patch load so it uses in-memory lines (no real file)
        with patch("src.jobs.job_manager.load", return_value=["G28", "M104", "M109"]):
            recovered = mgr2.recover()
        self.assertGreaterEqual(recovered, 1)


if __name__ == "__main__":
    unittest.main()