"""
Central runtime configuration for the Reactive Edge Hub.

Keep operational tuning values here instead of scattering them through
hardware, MQTT, job, telemetry, and vision modules.
"""

from pathlib import Path
import logging


# Logging
LOG_DIR = Path(__file__).resolve().parent.parent / "logs"
LOG_LEVEL = logging.DEBUG
LOG_MAX_BYTES = 5 * 1024 * 1024
LOG_BACKUP_COUNT = 3


# Serial hardware
SERIAL_PORT_PATTERNS = [
    "/tmp/ttyV0",
    "/dev/ttyUSB*",
    "/dev/ttyACM*",
]
SERIAL_BAUD_RATES = [115200, 250000]
SERIAL_STARTUP_STABILIZATION_DELAY_SEC = 3.0
SERIAL_READ_TIMEOUT_SEC = 5.0
SERIAL_RECONNECT_DELAY_SEC = 5.0
SERIAL_MAX_RECONNECT_ATTEMPTS = 5


# Serial router queues
SERIAL_ACK_QUEUE_SIZE = 128
SERIAL_TELEMETRY_QUEUE_SIZE = 256
SERIAL_ROUTER_STOP_TIMEOUT_SEC = 3.0


# Printer command protocol
PRINTER_COMMAND_TIMEOUT_SEC = 30.0
PRINTER_COMMAND_MAX_RETRIES = 2
PRINTER_COMMAND_RETRY_DELAY_SEC = 1.0
PRINTER_ACK_POLL_SEC = 0.1


# Command engine
COMMAND_RESULT_TIMEOUT_SEC = 30.0
COMMAND_PROCESSOR_STOP_TIMEOUT_SEC = 10.0
COMMAND_QUEUE_POLL_INTERVAL_SEC = 0.05
COMMAND_ERROR_RECOVERY_DELAY_SEC = 2.0
COMMAND_MAX_QUEUE_SIZE = 256
COMMAND_HISTORY_LIMIT = 500
COMMAND_MAX_LENGTH = 256
COMMAND_ALLOWED_PREFIXES = (
    "G",
    "M",
    "T",
    ";",
)


# Telemetry
TELEMETRY_IDLE_TIMEOUT_SEC = 5.0
TELEMETRY_STOP_TIMEOUT_SEC = 3.0
TELEMETRY_POLL_INTERVAL_SEC = 3.0
TELEMETRY_POLL_COMMANDS = ("M105", "M114")

# MQTT
MQTT_HOST_ENV = "MQTT_HOST"
MQTT_PORT_ENV = "MQTT_PORT"
MQTT_USERNAME_ENV = "MQTT_USERNAME"
MQTT_PASSWORD_ENV = "MQTT_PASSWORD"
MQTT_PRINTER_ID_ENV = "MQTT_PRINTER_ID"
MQTT_DEFAULT_PRINTER_ID = "printer-001"
MQTT_DEFAULT_CLIENT_ID_SUFFIX = "edge"
MQTT_DEFAULT_PORT = 8883
MQTT_BACKOFF_START_SEC = 2.0
MQTT_BACKOFF_MAX_SEC = 60.0
MQTT_OUTBOX_MAXSIZE = 256
MQTT_KEEPALIVE_SEC = 30
MQTT_STATE_PUBLISH_INTERVAL_SEC = 10.0
MQTT_ALLOWED_GCODE_PREFIXES = (
    "M104", "M109", "M140", "M190",
    "M105",
    "M106", "M107",
    "M112", "M108",
    "M84",
    "M114",
    "M115",
    "G0", "G1",
    "G28",
    "G29",
    "G90", "G91", "G92",
    "M25", "M24",
)
MQTT_REQUIRED_COMMAND_FIELDS = {"printerId", "commandName", "gcode", "commandLogId"}
MQTT_REQUIRED_START_JOB_FIELDS = {"printerId", "commandName", "jobId", "fileUrl"}


# Jobs
JOB_STORAGE_DIR = Path("data/jobs")
JOB_PAUSE_POLL_INTERVAL_SEC = 0.25


# Vision stream and sampling
VISION_CAMERA_URL_ENV = "VISION_CAMERA_URL"
VISION_DEFAULT_CAMERA_URL = "http://192.168.240.182:5000/video"
VISION_STREAM_RECONNECT_DELAY_SEC = 3.0
VISION_STREAM_READ_TIMEOUT_SEC = 5.0
VISION_FRAME_WAIT_TIMEOUT_SEC = 10.0
VISION_DEFAULT_SAMPLE_INTERVAL_SEC = 3.0
VISION_MIN_SAMPLE_INTERVAL_SEC = 1.0
VISION_MAX_SAMPLE_INTERVAL_SEC = 10.0
VISION_TARGET_WIDTH = 640
VISION_TARGET_HEIGHT = 480
VISION_JPEG_QUALITY = 75
VISION_INTERVAL_RISK_SEC = 1.5
VISION_INTERVAL_NORMAL_SEC = 3.0
VISION_INTERVAL_STABLE_SEC = 5.0
VISION_OK_STREAK_FOR_SLOW = 10


# Vision AI and safety thresholds
VISION_AI_ENDPOINT_ENV = "VISION_AI_ENDPOINT"
VISION_DEFAULT_AI_ENDPOINT = "http://192.168.240.182:2000/predict"
VISION_AI_TIMEOUT_SEC = 8.0
VISION_FAILURE_THRESHOLD = 3
VISION_CONFIDENCE_MIN = 0.75
VISION_COOLDOWN_SEC = 30.0


# Default printer metadata
PRINTER_NAME = "Creality Ender-3"
PRINTER_MODEL = "Ender-3"
PRINTER_NOZZLE_DIAMETER = 0.4
